name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v4

    - name: Build application
      run: |
        sh .devcontainer/post-create.sh
        cmake --preset wii
        cmake --build --preset wii --verbose

    - name: Prepare artifact
      run: |
        cmake --install build/wii --verbose --prefix /tmp/artifact

    - uses: actions/upload-artifact@v4
      with:
        name: Wii-Tac-Toe
        path: /tmp/artifact/
